
DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS groups;
-- DROP TABLE IF EXISTS menus;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR NOT NULL,
  user_group VARCHAR NOT NULL
);

CREATE TABLE groups (
  id INTEGER,
  name VARCHAR NOT NULL,
  permissions VARCHAR NOT NULL
);

CREATE TABLE menus (
  id INTEGER,
  name VARCHAR NOT NULL,
);
